import feladatok
import veletlenszam_listak

"""print(f"1. feladat\n{feladatok.feladat1([12,21,56,32,-5,-23,35])}")
print(f"2. feladat\n{feladatok.feladat2([12,21,56,32,-5,-23,35])}")
print(f"3. feladat\n{feladatok.feladat3([12,21,56,32,-5,-23,35])}")
lista=veletlenszam_listak.feladatlista()
print(f"Érme\n{lista}")
print(f"4. feladat\n{veletlenszam_listak.feladat4(lista)}")
dobasok = veletlenszam_listak.feladatdobasok()
print(f"Dobások:\n{dobasok}")
print(f"5.1 feladat\n{veletlenszam_listak.feladat5_1(dobasok)}")
print(f"5.2 feladat\n{veletlenszam_listak.feladat5_2(dobasok)}")
print(f"1. dobasok: {veletlenszam_listak.feladat5_3(dobasok,1)}")
print(f"2. dobasok: {veletlenszam_listak.feladat5_3(dobasok,2)}")
print(f"3. dobasok: {veletlenszam_listak.feladat5_3(dobasok,3)}")
print(f"4. dobasok: {veletlenszam_listak.feladat5_3(dobasok,4)}")
print(f"5. dobasok: {veletlenszam_listak.feladat5_3(dobasok,5)}")
print(f"6. dobasok: {veletlenszam_listak.feladat5_3(dobasok,6)}")"""
print(f"Cinkelt kockás dobások: \n{veletlenszam_listak.feladatcinkelt()}")
dobasok2 = veletlenszam_listak.feladatcinkelt()
print(f"1. dobasok: {veletlenszam_listak.feladat6(dobasok2,1)}")
print(f"2. dobasok: {veletlenszam_listak.feladat6(dobasok2,2)}")
print(f"3. dobasok: {veletlenszam_listak.feladat6(dobasok2,3)}")
print(f"4. dobasok: {veletlenszam_listak.feladat6(dobasok2,4)}")
print(f"5. dobasok: {veletlenszam_listak.feladat6(dobasok2,5)}")
print(f"6. dobasok: {veletlenszam_listak.feladat6(dobasok2,6)}")